// <auto-generated />
using System;
using BeaconRelay.LpdReceiver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeaconRelay.LpdReceiver.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529160257_AddRuleHighlightColor")]
    partial class AddRuleHighlightColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.DeliveryAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BytesSentOrCopied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueNameUsed")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteHost")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemotePort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCreatedPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Outcome");

                    b.HasIndex("StartedUtc");

                    b.HasIndex("WorkItemId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("DeliveryAttempts");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.DeliveryPauseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PausedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResumeAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPauseState");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.DeliveryWorkItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReceivedFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationType");

                    b.HasIndex("LockExpiresUtc");

                    b.HasIndex("ReceivedFileId");

                    b.HasIndex("RuleId");

                    b.HasIndex("Status", "NextAttemptUtc", "Priority");

                    b.ToTable("DeliveryWorkItems");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.ProcessingRuleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HighlightColor")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchOperator")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueMatchType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueMatchValue")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIpCidr")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("StopProcessingOnMatch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VirtualPrinterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Priority");

                    b.HasIndex("VirtualPrinterId");

                    b.ToTable("ProcessingRules");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.PurgePolicyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplyTo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TerminalStatusesCsv")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PurgePolicies");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.ReceivedFileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerClass")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DuplicateOfId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LpdJobId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawControlText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteHost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("RemotePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileHints")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LpdJobId");

                    b.HasIndex("ReceivedUtc");

                    b.HasIndex("Sha256");

                    b.HasIndex("Status");

                    b.ToTable("ReceivedFiles");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.RetentionSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RetentionSettings");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.RetryPolicyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackoffMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JitterPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RetryPolicies");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.RuleFolderDestinationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DuplicatePolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQueueOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetryPolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootFolder")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubfolderPattern")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubfolderPatternType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueNameAffix")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueNameMode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("RetryPolicyId");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleFolderDestinations");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.RuleForwardDestinationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompressMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutboundQueueName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetryPolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("RetryPolicyId");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleForwardDestinations");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.VirtualPrinterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("ListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VirtualPrinterName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListenPort");

                    b.HasIndex("QueueName");

                    b.HasIndex("VirtualPrinterName")
                        .IsUnique();

                    b.ToTable("VirtualPrinters");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.DeliveryAttemptRecord", b =>
                {
                    b.HasOne("BeaconRelay.LpdReceiver.Data.DeliveryWorkItemRecord", "WorkItem")
                        .WithMany("Attempts")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.DeliveryWorkItemRecord", b =>
                {
                    b.HasOne("BeaconRelay.LpdReceiver.Data.ReceivedFileRecord", "ReceivedFile")
                        .WithMany()
                        .HasForeignKey("ReceivedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeaconRelay.LpdReceiver.Data.ProcessingRuleRecord", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceivedFile");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.ProcessingRuleRecord", b =>
                {
                    b.HasOne("BeaconRelay.LpdReceiver.Data.VirtualPrinterRecord", "VirtualPrinter")
                        .WithMany()
                        .HasForeignKey("VirtualPrinterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VirtualPrinter");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.RuleFolderDestinationRecord", b =>
                {
                    b.HasOne("BeaconRelay.LpdReceiver.Data.RetryPolicyRecord", "RetryPolicy")
                        .WithMany()
                        .HasForeignKey("RetryPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeaconRelay.LpdReceiver.Data.ProcessingRuleRecord", "Rule")
                        .WithMany("FolderDestinations")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetryPolicy");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.RuleForwardDestinationRecord", b =>
                {
                    b.HasOne("BeaconRelay.LpdReceiver.Data.RetryPolicyRecord", "RetryPolicy")
                        .WithMany("ForwardDestinations")
                        .HasForeignKey("RetryPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BeaconRelay.LpdReceiver.Data.ProcessingRuleRecord", "Rule")
                        .WithMany("ForwardDestinations")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetryPolicy");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.DeliveryWorkItemRecord", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.ProcessingRuleRecord", b =>
                {
                    b.Navigation("FolderDestinations");

                    b.Navigation("ForwardDestinations");
                });

            modelBuilder.Entity("BeaconRelay.LpdReceiver.Data.RetryPolicyRecord", b =>
                {
                    b.Navigation("ForwardDestinations");
                });
#pragma warning restore 612, 618
        }
    }
}
